# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/CMakeConfigurableFile.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/CheckFortranFunctionExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/CheckFunctionExists.c))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/CheckFunctionExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/CheckIncludeFile.c.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/CheckIncludeFileCXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/CheckSymbolExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/CheckTypeSize.c.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/CheckTypeSize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindGIF.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindJPEG.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindPNG.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindPkgConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindX11.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindZLIB.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.12/Modules/SelectLibraryConfigurations.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/ken/projects/dlib/v-19.15-Xcode/dlib-19.15/dlib/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/ken/projects/dlib/v-19.15-Xcode/dlib-19.15/dlib/cmake_utils/find_blas.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/ken/projects/dlib/v-19.15-Xcode/dlib-19.15/dlib/cmake_utils/release_build_by_default))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/ken/projects/dlib/v-19.15-Xcode/dlib-19.15/dlib/cmake_utils/set_compiler_specific_options.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/ken/projects/dlib/v-19.15-Xcode/dlib-19.15/dlib/cmake_utils/use_cpp_11.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/ken/projects/dlib/v-19.15-Xcode/dlib-19.15/examples/build/CMakeFiles/CheckTypeSize/SIZE_OF_VOID_PTR.c))

/Users/ken/projects/dlib/v-19.15-Xcode/dlib-19.15/examples/build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/ken/projects/dlib/v-19.15-Xcode/dlib-19.15/examples -B/Users/ken/projects/dlib/v-19.15-Xcode/dlib-19.15/examples/build
